language: go

go:
  1.7.x

dist: trusty
sudo: required

before_install:
  - echo KERNEL==\"uinput\", GROUP=\"$USER\", MODE:=\"0660\" | sudo tee /etc/udev/rules.d/99-$USER.rules
  - sudo udevadm trigger